name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: Install dependencies and run tests
        run: |
          npm install
          npm run test
  publish:
    needs: [cypress-run]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results
